on:
  push:

jobs:
  test-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue
        run: |
          echo ${{ secrets.ISSUE_TEST_TOKEN }} | gh auth login --with-token

          gh issue create --title 'Test issue' --body 'test test test' --label 'test-label'
